version: '3.8'
services:
  flask-app:
    container_name: flask-container
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"  # Prometheus metrics
    networks:
      - monitoring

  prometheus:
    container_name: prometheus-container
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
  
  grafana:
    container_name: grafana-container
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password
    ports:
      - "3000:3000"  # Grafana web UI
    networks:
      - monitoring
    depends_on:
      - prometheus  # Ensure Prometheus starts before Grafana

networks:
  monitoring:
