version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"  # Prometheus metrics
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

networks:
  monitoring:
